//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team13_UV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UV_Data
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public double UV_Index { get; set; }
    }
}
